EvSef.Web/Controllers/ChefController.cs
using EvSef.Core.Services.Implementations;
using EvSef.Core.Services.Interfaces;
using EvSef.Domain.ViewModels.Chef;
using EvSef.Domain.ViewModels.SiteSetting;
using Microsoft.AspNetCore.Mvc;

namespace EvSef.Web.Controllers
{
    
    public class ChefController : SiteBaseController 
    {
        #region Constructor

        private readonly IUserService _userService;
        private readonly ISiteService _siteService;

        public ChefController(IUserService userService, ISiteService siteService)
        {
            _userService = userService;
            _siteService = siteService;
        }

        #endregion

        [HttpGet]
        [Route("ChefRequest")]
        public async Task<IActionResult> CreateChefRequestInSite()
        {
            var state = await _siteService.GetStates();
            ViewData["State"] = state;

            var firstLocationId = state.First().LocationId;
            var district = await _siteService.GetDistricts(firstLocationId);
            ViewData["District"] = district;

            SiteSettingViewModel? siteSetting = await _siteService.GetSiteSettingForEdit();
            var beChefTitle = siteSetting.BeChefTitle;
            ViewData["BeChefTitle"] = beChefTitle;

            var beChefDescription = siteSetting.BeChefDescription;
            ViewData["BeChefDescription"] = beChefDescription;

            var chefImage = siteSetting.BeChefImage;
            ViewData["ChefImage"] = chefImage;



            return View();
        }

        [HttpPost]
        [Route("ChefRequest")]
        public async Task<IActionResult> CreateChefRequestInSite(ChefRequestInSitViewModel registerNewChefInSitViewModel)
        {

            SiteSettingViewModel? siteSetting = await _siteService.GetSiteSettingForEdit();
            var beChefTitle = siteSetting.BeChefTitle;
            ViewData["BeChefTitle"] = beChefTitle;

            var beChefDescription = siteSetting.BeChefDescription;
            ViewData["BeChefDescription"] = beChefDescription;

            var result = await _userService.CreateChefRequestInSite(registerNewChefInSitViewModel);

            switch (result)
            {
                case ChefRequestInSiteResult.Failed:
                    return RedirectToAction("NotFound");

                case ChefRequestInSiteResult.UserHasRequestWithThisNumber:
                    ModelState.AddModelError("Email", "You have sent a request Before, Please Wait our Staff calling you!");
                    await GetStateAndDistricts();
                    return View(registerNewChefInSitViewModel);
                case ChefRequestInSiteResult.Successfully:
                    TempData[SuccessMessage] = "Your Request was sent, Please wait to Our call !";
                    return RedirectToAction("Index", "Home");

            }
            await GetStateAndDistricts();
            ViewBag.ErrorText = "Your Request Was Not Created Successfully";
            return View(registerNewChefInSitViewModel);
        }

        public async Task GetStateAndDistricts()
        {
            var state = await _siteService.GetStates();
            ViewData["State"] = state;

            var firstLocationId = state.First().LocationId;
            var district = await _siteService.GetDistricts(firstLocationId);
            ViewData["District"] = district;

        }

        public async Task<IActionResult> GetDistrictGroup(int id)
        {
            var district = await _siteService.GetDistricts(id);
            return Json(district);
        }
    }
}

EvSef.Web/Areas/AdminPanel/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "NotFound";
    Layout = "_AdminLayout";
}

<h1>NotFound</h1>


<div class="login-form-bg h-100">
    <div class="container h-100">
        <div class="row justify-content-center h-100">
            <div class="col-xl-6">
                <div class="error-content">
                    <div class="card mb-0">
                        <div class="card-body text-center">
                            <h1 class="error-text text-primary">400</h1>
                            <h4 class="mt-4"><i class="fa fa-thumbs-down text-danger"></i> Bad Request</h4>
                            <p>Your Request resulted in an error.</p>
                            <form class="mt-5 mb-5">

                                <div class="text-center mb-4 mt-4">
                                    <a href="index.html" class="btn btn-primary">Go to Homepage</a>
                                </div>
                            </form>
                            <div class="text-center">
                                <p>Copyright © Designed by <a href="https://evsef.com">EvŞef</a>, Developed by <a href="https://evsef.com">EvŞef</a> 2024</p>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <a href="javascript:void()" class="btn btn-facebook"><i class="fa fa-facebook"></i></a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="javascript:void()" class="btn btn-twitter"><i class="fa fa-twitter"></i></a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="javascript:void()" class="btn btn-linkedin"><i class="fa fa-linkedin"></i></a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="javascript:void()" class="btn btn-google-plus"><i class="fa fa-google-plus"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

EvSef.Web/Areas/AdminPanel/Views/Shared/Scripts.cshtml
<script src="~/Panel/plugins/common/common.min.js"></script>
<script src="~/Panel/js/custom.min.js"></script>
<script src="~/Panel/js/settings.js"></script>
<script src="~/Panel/js/gleek.js"></script>
<script src="~/Panel/js/styleSwitcher.js"></script>

<!-- Date range Plugin JavaScript -->

<script src="~/Panel/js/plugins-init/form-pickers-init.js"></script>
<script src="~/Panel/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script src="~/Panel/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>

<script src="~/Panel/plugins/moment/moment.js"></script>
<script src="~/Panel/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>


<!-- Chartjs -->
<script src="~/Panel/plugins/chart.js/Chart.bundle.min.js"></script>
<!-- Circle progress -->
<script src="~/Panel/plugins/circle-progress/circle-progress.min.js"></script>
<!-- Datamap -->
<script src="~/Panel/plugins/d3v3/index.js"></script>
<script src="~/Panel/plugins/topojson/topojson.min.js"></script>
<script src="~/Panel/plugins/datamaps/datamaps.world.min.js"></script>
<!-- Morrisjs -->
<script src="~/Panel/plugins/raphael/raphael.min.js"></script>
<script src="~/Panel/plugins/morris/morris.min.js"></script>
<!-- Pignose Calender -->
<script src="~/Panel/plugins/moment/moment.min.js"></script>
<script src="Panel/plugins/pg-calendar/js/pignose.calendar.min.js"></script>
<!-- ChartistJS -->
<script src="~/Panel/plugins/chartist/js/chartist.min.js"></script>
<script src="~/Panel/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js"></script>

 

<script src="~/Panel/js/dashboard/dashboard-1.js"></script>
 
@*   <script src="~/Panel/plugins/sweetalert2/dist/sweetalert2.min.js"></script>
 *@
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7/dist/sweetalert2.all.min.js"></script>

<script src="/js/modules.js"></script>
 
 


<!-- Clock Plugin JavaScript -->
<script src="~/Panel/plugins/clockpicker/dist/jquery-clockpicker.min.js"></script>
<!-- Color Picker Plugin JavaScript -->
<script src="~/Panel/plugins/jquery-asColorPicker-master/libs/jquery-asColor.js"></script>
<script src="~/Panel/plugins/jquery-asColorPicker-master/libs/jquery-asGradient.js"></script>
<script src="~/Panel/plugins/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js"></script>
<!-- Date Picker Plugin JavaScript -->
<script src="~/Panel/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<!-- Date range Plugin JavaScript -->
<script src="~/Panel/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script src="~/Panel/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>

<script src="~/Panel/js/plugins-init/form-pickers-init.js"></script>





<!-- Date range Plugin JavaScript -->

<script src="~/Panel/js/plugins-init/form-pickers-init.js"></script>
<script src="~/Panel/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script src="~/Panel/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>

<script src="~/Panel/plugins/moment/moment.js"></script>
<script src="~/Panel/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>


<!-- Chartjs -->
<script src="~/Panel/plugins/chart.js/Chart.bundle.min.js"></script>
<!-- Circle progress -->
<script src="~/Panel/plugins/circle-progress/circle-progress.min.js"></script>
<!-- Datamap -->
<script src="~/Panel/plugins/d3v3/index.js"></script>
<script src="~/Panel/plugins/topojson/topojson.min.js"></script>
<script src="~/Panel/plugins/datamaps/datamaps.world.min.js"></script>
<!-- Morrisjs -->
<script src="~/Panel/plugins/raphael/raphael.min.js"></script>
<script src="~/Panel/plugins/morris/morris.min.js"></script>
<!-- Pignose Calender -->
<script src="~/Panel/plugins/moment/moment.min.js"></script>
<script src="Panel/plugins/pg-calendar/js/pignose.calendar.min.js"></script>
<!-- ChartistJS -->
<script src="~/Panel/plugins/chartist/js/chartist.min.js"></script>
<script src="~/Panel/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js"></script>

 

<script src="~/Panel/js/dashboard/dashboard-1.js"></script>
 
@*   <script src="~/Panel/plugins/sweetalert2/dist/sweetalert2.min.js"></script>
 *@
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7/dist/sweetalert2.all.min.js"></script>

<script src="~/js/modules.js"></script>
 
 


<!-- Clock Plugin JavaScript -->
<script src="~/Panel/plugins/clockpicker/dist/jquery-clockpicker.min.js"></script>
<!-- Color Picker Plugin JavaScript -->
<script src="~/Panel/plugins/jquery-asColorPicker-master/libs/jquery-asColor.js"></script>
<script src="~/Panel/plugins/jquery-asColorPicker-master/libs/jquery-asGradient.js"></script>
<script src="~/Panel/plugins/jquery-asColorPicker-master/dist/jquery-asColorPicker.min.js"></script>
<!-- Date Picker Plugin JavaScript -->
<script src="~/Panel/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<!-- Date range Plugin JavaScript -->
<script src="~/Panel/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script src="~/Panel/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>

<script src="~/Panel/js/plugins-init/form-pickers-init.js"></script>

EvSef.Web/Areas/AdminPanel/Views/Shared/Styles.cshtml
 <!-- Favicon icon -->
<link rel="icon" type="image/png" sizes="16x16" href="/Panel/images/favicon.png">
<!-- Pignose Calender -->
<link href="/Panel/plugins/pg-calendar/css/pignose.calendar.min.css" rel="stylesheet">
<!-- Chartist -->
<link rel="stylesheet" href="/Panel/plugins/chartist/css/chartist.min.css">
<link rel="stylesheet" href="/Panel/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css">
<!-- Custom Stylesheet -->
<link href="/Panel/css/style.css" rel="stylesheet">
 
<link href="~/panel/icons/font-awesome/css/all.css" rel="stylesheet" />
 <link href="~/panel/icons/font-awesome/css/all.min.css" rel="stylesheet" />

<link href="~/panel/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet">



 <!-- Custom Stylesheet -->
<link href="~/panel/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet">
 <!-- Page plugins css -->
<link href="~/panel/plugins/clockpicker/dist/jquery-clockpicker.min.css" rel="stylesheet">
 <!-- Color picker plugins css -->
<link href="~/panel/plugins/jquery-asColorPicker-master/css/asColorPicker.css" rel="stylesheet">
 
 

EvSef.Web/Areas/AdminPanel/Views/Shared/_AdminLayout.cshtml
<html lang="en">
<head>

    <partial name="_MetaTags" />

    <title>Admin Panel | @ViewData["Title"] </title>
   
    <partial name="_HeaderReferences" />
    <partial name="Styles" />
    @RenderSection("Styles", false)
</head>


<body>
    <div id="main-wrapper">
        <!-- Page Loader Partial -->
        <partial name="_Pageloader" />

        <!--NavBarHead Partial-->
        <partial name="_NavBarHead" />

        <!--Header Partial-->
        <partial name="_Header" />

        <!--LeftSideBar Partial-->
        <partial name="_LeftSidebar" />


        <!-- Main Content -->
        @RenderBody()

        <!-- Footer Partial-->

        <partial name="_Footer" />
     
        <!-- Scripts Partial -->
        <partial name="Scripts" />

        @RenderSection("Scripts", false)
     
        <partial name="_ValidationScriptsPartial" />
        
    </div>
</body>


</html>

EvSef.Web/Areas/AdminPanel/Views/Shared/_Footer.cshtml
<div class="footer fixed-bottom">
    <div class="row">
        <div class="col-md-12 text-center">
            <p>
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved |
                <i class="icon-heart" aria-hidden="true"></i> by
                <a href="https://EvŞef.com" target="_blank">Ev Şef</a>
            </p>
        </div>
    </div>
</div>

EvSef.Web/Areas/AdminPanel/Views/Shared/_Header.cshtml
 
<div class="header">
    <div class="header-content clearfix">

        <div class="nav-control">
            <div class="hamburger">
                <span class="toggle-icon"><i class="icon-menu"></i></span>
            </div>
        </div>
        <div class="header-left">
            <div class="input-group icons">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-transparent border-0 pr-2 pr-sm-3" id="basic-addon1"><i class="mdi mdi-magnify"></i></span>
                </div>
                <input type="search" class="form-control" placeholder="Search Dashboard" aria-label="Search Dashboard">
                <div class="drop-down animated flipInX d-md-none">
                    <form action="#">
                        <input type="text" class="form-control" placeholder="Search">
                    </form>
                </div>
            </div>
        </div>
        <div class="header-right">
            <ul class="clearfix">
                <li class="icons dropdown">
                    <a href="javascript:void(0)" data-toggle="dropdown">
                        <i class="mdi mdi-email-outline"></i>
                        <span class="badge badge-pill gradient-1 ">4</span>
                    </a>
                    <div class="drop-down animated fadeIn dropdown-menu">
                        <div class="dropdown-content-heading d-flex justify-content-between">
                            <span class=" ">3 New Messages</span>
                            <a href="javascript:void()" class="d-inline-block">
                                <span class="badge badge-pill gradient-1 ">3</span>
                            </a>
                        </div>
                        <div class="dropdown-content-body">
                            <ul>
                                <li class="notification-unread">
                                    <a href="javascript:void()">
                                        <img class="float-left mr-3 avatar-img" src="Panel/images/avatar/1.jpg" alt="">
                                        <div class="notification-content">
                                            <div class="notification-heading">Saiful Islam</div>
                                            <div class="notification-timestamp">08 Hours ago</div>
                                            <div class="notification-text">Hi Teddy, Just wanted to let you ...</div>
                                        </div>
                                    </a>
                                </li>
                                <li class="notification-unread">
                                    <a href="javascript:void()">
                                        <img class="float-left mr-3 avatar-img" src="Panel/images/avatar/2.jpg" alt="">
                                        <div class="notification-content">
                                            <div class="notification-heading">Adam Smith</div>
                                            <div class="notification-timestamp">08 Hours ago</div>
                                            <div class="notification-text">Can you do me a favour?</div>
                                        </div>
                                    </a>
                                </li>

                            </ul>

                        </div>
                    </div>
                </li>
               
                <li class="icons dropdown d-none d-md-flex">
                    <a href="javascript:void(0)" class="log-user" data-toggle="dropdown">
                        <span>English</span>  <i class="fa fa-angle-down f-s-14" aria-hidden="true"></i>
                    </a>
                    <div class="drop-down dropdown-language animated fadeIn  dropdown-menu">
                        <div class="dropdown-content-body">
                            <ul>
                                <li><a href="javascript:void()">English</a></li>
                                <li><a href="javascript:void()">Turkey</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
                <li class="icons dropdown">
                    <div class="user-img c-pointer position-relative" data-toggle="dropdown">
                        <span class="activity active"></span>
                        <img src="/Panel/images/user/1.png" height="40" width="40" alt="">
                    </div>
                    <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                        <div class="dropdown-content-body">
                            <ul>
                                <li>
                                    <a href="app-profile.html"><i class="icon-user"></i> <span>Profile</span></a>
                                </li>
                                <li>
                                    <a href="javascript:void()">
                                        <i class="icon-envelope-open"></i> <span>Inbox</span> <div class="badge gradient-3 badge-pill gradient-1">3</div>
                                    </a>
                                </li>

                                <hr class="my-2">
                                <li>
                                    <a href="page-lock.html"><i class="icon-lock"></i> <span>Lock Screen</span></a>
                                </li>
                                <li><a href="page-login.html"><i class="icon-key"></i> <span>Logout</span></a></li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
 

EvSef.Web/Areas/AdminPanel/Views/Shared/_HeaderReferences.cshtml
 
<link href="~/panel/plugins/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet" />
 

EvSef.Web/Areas/AdminPanel/Views/Shared/_LeftSidebar.cshtml
 

<div class="nk-sidebar  ">
    <div class="nk-nav-scroll">
        <ul class="metismenu" id="menu">

           @*  <li class="nav-label">Dashboard</li> *@
            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-speedometer menu-icon"></i><span class="nav-text">Dashboard</span>
                </a>
                <ul aria-expanded="false">
                    <li>  <a asp-controller="Home" asp-action="index">Home</a></li>
                    <!-- <li><a href="./index-2.html">Home 2</a></li> -->
                </ul>
            </li>
            @*
            <li class="nav-label">Users</li> *@

            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fa fa-user "></i><span class="nav-text">Users</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-controller="User" asp-action="Index">User List</a></li>
                    <li><a asp-controller="User" asp-action="CreatePersonByAdmin">New User</a></li>
                    <li><a >Custom Food Request</a></li>
                </ul>

            </li>

            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fa fa-users "></i><span class="nav-text">Corporations</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-controller="Corporation" asp-action="Index">Request Corporations</a></li>
                    <li><a asp-controller="Corporation" asp-action="CorporationList">Corporation List</a></li>
                    <li><a asp-controller="Corporation" asp-action="CreateCorporationByAdmin">New Corporation</a></li>

                </ul>

            </li>


            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fa fa-female"></i><span class="nav-text">Chef</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-controller="Chef" asp-action="Index">Request Chef List</a></li>
                    <li><a asp-controller="Chef" asp-action="FilterChefList">Chef List</a></li>
                    <li><a asp-controller="Chef" asp-action="CreateNewChef">New Chef</a></li>

                </ul>
            </li>
       
            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fa fa-cutlery "></i><span class="nav-text">Food</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-controller="Food" asp-action="FilterFoodList">Food List</a></li>
                    <li><a asp-controller="Food" asp-action="CreateFoodByAdmin">New Food</a></li>
                    <li><a asp-controller="Food" asp-action="Index"> - Food Category List</a></li>
                    <li><a asp-controller="Food" asp-action="CreateFoodCategoryByAdmin"> - New Food Category</a></li>
                    <li><a asp-controller="Food" asp-action="FoodSettingList">   <i class="fa  fa-cog fa-lg"></i>Food Setting</a></li>
                 
                </ul>
            </li>
            
           
           <li class="mega-menu mega-menu-sm">
               <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                   <i class="fa fa-heartbeat "></i><span class="nav-text">Custom Food</span>
               </a>
               <ul aria-expanded="false">
                   <li><a asp-controller="CustomFood" asp-action="Index" >Custom Food List </a></li>
                   <li><a asp-controller="CustomFood" asp-action="CreateCustomFoodByAdmin">New Custom Food</a></li>
            
                
               </ul>
           </li>

           <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fas fa-hamburger "></i><span class="nav-text">Daily Menu</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-controller="WeekDayFood" asp-action="Index">Daily Menu List</a></li>
                    <li><a asp-controller="WeekDayFood"  asp-action="CreateWeekDayFoodByAdmin">New Daily Menu</a></li>
                
                </ul>
            </li>
            
      
           <li class="mega-menu mega-menu-sm">
               <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                   <i class="fas fa-people-carry"></i><span class="nav-text">Our Service</span>
               </a>
               <ul aria-expanded="false">
                   <li><a asp-controller="OurService" asp-action="Index">Our Service List</a></li>
                   <li><a asp-controller="OurService" asp-action="CreateOurServiceByAdmin">New Our Service</a></li>
               </ul>
            
           </li>
          
            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fas fa-building"></i><span class="nav-text">Corporation Food</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-controller="CorporationFoodOrder" asp-action="CorporationFoodOrderList">How Order? List</a></li>
                    <li><a asp-controller="CorporationFoodOrder" asp-action="CreateCorporationFoodOrderByAdmin">New How Order </a></li>
                </ul>
            </li>
            
            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fa fa-spoon "></i><span class="nav-text">Cooking Page</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-controller="JoinUs" asp-action="Index">Join Us List</a></li>
                 </ul>
                <ul aria-expanded="false">
                    <li><a  asp-controller="BeComeChef"  asp-action="Index">Become a Chef List</a></li>
                </ul>
            </li>
            
            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fas fa-store"></i><span class="nav-text">Restaurants</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-controller="Restaurant" asp-action="Index">Restaurants List</a></li>
                    <li><a asp-controller="Restaurant" asp-action="CreateRestaurantByAdmin">New Restaurant</a></li>
                </ul>
            
            </li>

           <li class="mega-menu mega-menu-sm">
               <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                   <i class="fa fa-handshake-o "></i><span class="nav-text">Our Customers</span>
               </a>
               <ul aria-expanded="false">
                   <li><a asp-controller="OurCustomer" asp-action="index" >Our Customers List</a></li>
                   <li><a asp-controller="OurCustomer" asp-action="CreateOurCustomer">New Customer</a></li>
               </ul>
           </li>


            <li class="mega-menu mega-menu-sm">
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fa fa-cog"></i><span class="nav-text">Site Setting</span>
                </a>
                <ul aria-expanded="false">
                    <li><a asp-controller="SiteSetting" asp-action="Index">Website</a></li>
                    <li><a asp-controller="AboutUs" asp-action="Index">About Us</a></li>
                    <li><a asp-controller="MainSlider" asp-action="Index">Main Slider</a></li>
                    <li><a asp-controller="SocialMedia" asp-action="Index">Social Media</a></li>
                    <li><a asp-controller="Instagram" asp-action="Index">Instagram Post</a></li>
                </ul>
            </li>

            
           <li class="mega-menu mega-menu-sm">
               <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fa fa-question-circle"></i><span class="nav-text">F.A.Q</span>
               </a>
               <ul aria-expanded="false">
                   <li><a >User Help</a></li>
               </ul>

           </li>
        </ul>
    </div>
</div>

EvSef.Web/Areas/AdminPanel/Views/Shared/_MetaTags.cshtml
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,initial-scale=1">

EvSef.Web/Areas/AdminPanel/Views/Shared/_NavBarHead.cshtml
<div class="nav-header">
    <div class="brand-logo">
        <a  asp-controller="Home" asp-action="index">
            <b class="brand-title logo-text ml-1"><span class="font-weight-bold"> Ev Şef</span> </b>
            <!--<span class="logo-compact"><img src="./images/logo.ico" alt="" width="20" height="20" ></span>-->
            <span class="">
                <img src="/panel/images/logo.ico" alt="" width="50" height="50">
            </span>
        </a>
    </div>
</div>

EvSef.Web/Areas/AdminPanel/Views/Shared/_Pageloader.cshtml
 

<div id="preloader">
    <div class="loader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
        </svg>
    </div>
</div>