EvSef.Web/Areas/AdminPanel/Controllers/FoodController.cs
using System.Reflection.Metadata.Ecma335;
using EvSef.Core.Services.Implementations;
using EvSef.Core.Services.Interfaces;
using EvSef.Domain.Entities.Food;
using EvSef.Domain.IRepository;
using EvSef.Domain.ViewModels.Food;
using EvSef.Domain.ViewModels.FoodCategory;
using EvSef.Domain.ViewModels.PriceType;
using Microsoft.AspNetCore.Mvc;

namespace EvSef.Web.Areas.AdminPanel.Controllers
{
    public class FoodController : BaseAdminController
    {
        #region Constructor

        private readonly IFoodService _foodService;

        public FoodController(IFoodService foodService)
        {
            _foodService = foodService;
        }

        #endregion

        #region FilterFood Category

        [HttpGet]
        [Route("FoodCategoryList")]
        public async Task<IActionResult> Index(FilterFoodCategoryViewModel filterFoodCategoryViewModel)
        {
            var result =  await _foodService.FilterFoodCategoryList(filterFoodCategoryViewModel);
            return  View(result);
        }



        #endregion

        #region CreateFoodCategory By Admin

        [HttpGet]
        [Route("CreateFoodCategory")]
        public  IActionResult  CreateFoodCategoryByAdmin()
        {
            return View();
        }

        [HttpPost]
        [Route("CreateFoodCategory")]

        public async Task<IActionResult> CreateFoodCategoryByAdmin(CreateFoodCategoryViewModel createFoodCategoryViewModel)
        {

            if (ModelState.IsValid)
            {
                var result = await _foodService.CreateFoodCategoryByAdmin(createFoodCategoryViewModel);

                switch (result)
                {
                    case CreateFoodCategoryResult.FoodCategoryIsExist:
                        ModelState.AddModelError("FoodCategoryTitle", "Food Category Title is Exists");
                        return View(createFoodCategoryViewModel);

                    case CreateFoodCategoryResult.NotFound:
                        return RedirectToAction("NotFound");

                    case CreateFoodCategoryResult.Success:
                        return RedirectToAction("Index");
                }
            }

            return View(createFoodCategoryViewModel);
        }

        #endregion

        #region FilterFood List

        [HttpGet]
        [Route("Food List")]
        public async Task<IActionResult> FilterFoodList(FilterFoodViewModel filterFoodViewModel )
        {
            var result = await _foodService.FilterFoodList(filterFoodViewModel);
            await GetFoodsWithCategories();
            return View(result);
        }

        #endregion

        #region Create Food

        [HttpGet]
        [Route("CreateFood")]
        public async Task<IActionResult> CreateFoodByAdmin()
        {
            await GetFoodCategory();
             
            return View();
        }

        [HttpPost]
        [Route("CreateFood")]

        public async Task<IActionResult> CreateFoodByAdmin(CreateFoodViewModel createFoodViewModel)
        {

            if (ModelState.IsValid)
            {
                
                var result = await _foodService.CreateFoodByAdmin(createFoodViewModel);

                switch (result)
                {
                    case CreateFoodResult.FoodIsExist:
                        await GetFoodCategory();
                        ModelState.AddModelError("FoodTitle", "Food Title is Exists");
                        return View(createFoodViewModel);

                    case CreateFoodResult.NotFound:
                        return RedirectToAction("NotFound");

                    case CreateFoodResult.Success:
                        return RedirectToAction("FilterFoodList");
                }
            }

            await GetFoodCategory();
            return View(createFoodViewModel);
        }


        #endregion

        #region Get FoodCategory

        public async Task GetFoodCategory()
        {
            var foodCategory = await _foodService.GetAllFoodCategory();
            ViewData["FoodCategory"] = foodCategory;
        }

        
        public  async Task GetFoodsWithCategories()
        {
            var viewModel = await _foodService.GetFoodsWithCategories();
            ViewData["FilterFoodViewModel"] = viewModel;
             
        }
        #endregion

        #region Create FoodSetting ByAdmin

        [HttpGet]
        [Route("CreateFoodSetting")]
        public IActionResult CreateFoodSettingByAdmin()
        {
            return View();
        }

        [HttpPost]
        [Route("CreateFoodSetting")]

        public async Task<IActionResult> CreateFoodSettingByAdmin(CreatePriceTypeViewModel createPriceTypeViewModel)
        {

            if (ModelState.IsValid)
            {
                var result = await _foodService.CreateFoodSettingByAdmin(createPriceTypeViewModel);

                switch (result)
                {
                    case CreatePriceTypeResult.PriceTypeIsExist:
                        ModelState.AddModelError("PriceTypename", "Price type name is Exists");
                        return View(createPriceTypeViewModel);

                    case CreatePriceTypeResult.NotFound:
                        return RedirectToAction("NotFound");

                    case CreatePriceTypeResult.Success:
                        return RedirectToAction("FoodSettingList");
                }
            }

            return View(createPriceTypeViewModel);
        }


        #endregion

        #region FoodSetting List


        [HttpGet]
        [Route("FoodSettingList")]
        public async Task<IActionResult> FoodSettingList()
        {
            var result = await _foodService.FoodSettingList();
            return View(result);
        }

        #endregion



    }
}

EvSef.Web/Areas/AdminPanel/Views/Food/CreateFoodByAdmin.cshtml
@using EvSef.Domain.Entities.Food
@using EvSef.Domain.ViewModels.FoodCategory
@model EvSef.Domain.ViewModels.Food.CreateFoodViewModel
@{
    ViewData["Title"] = "Create Food ByAdmin";
    List<FoodCategoryViewModel>? foodCategory = ViewData["FoodCategory"] as List<FoodCategoryViewModel>;
}


<div class="row page-titles mx-0">
    <div class="col p-md-0">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Dashboard</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Create Food</a></li>
        </ol>
    </div>
</div>


<div class="content-body">

    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="basic-form">
                            <form asp-controller="food" asp-action="CreateFoodByAdmin" method="post" enctype="multipart/form-data">
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label asp-for="FoodTitle">Food Title</label>
                                        <input asp-for="FoodTitle" type="text" class="form-control">
                                        <span asp-validation-for="FoodTitle"></span>
                                    </div>


                                    <div class="form-group col-md-6">
                                        <label asp-for="FoodAvatar">Food Avatar</label>
                                        <input asp-for="FoodAvatar" class="form-control" placeholder="Avatar">
                                        <span asp-validation-for="FoodAvatar"></span>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <label asp-for="FoodDescription">Food Description</label>
                                    <textarea asp-for="FoodDescription" type="text" class="form-control"></textarea>
                                    <span asp-validation-for="FoodDescription"></span>
                                </div>

                                <div class="form-group">
                                    <div class="form-check">
                                        <input id="checkbox"  class="form-check-input" type="checkbox" asp-for="IsActive">
                                        <label for="checkbox" class="form-check-label">Active</label>
                                    </div>
                                </div>
                                
                                @if (foodCategory != null)
                                {
                                    <div class="form-group">
                                        <div class="form-check">

                                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                            <label >Food Category Lis</label>

                                            <ul>
                                       
                                                @foreach (var foodCat in foodCategory)
                                                {
                                                    <li >
                                                        <input class="form-check-input" name="SelectedFoodCategory" type="checkbox" value="@foodCat.FoodCategoryId" id="categoryCheckbox">
                                                        <label for="categoryCheckbox">@foodCat.FoodCategoryTitle</label>
                                                    </li>
                                                }
                                                <span asp-validation-for="SelectedFoodCategory"></span>
                                            </ul>
                                        </div>
                                    </div>

                                }
                           

                                <div class="col-md-12 col-sm-12">
                                    <div class=" ">
                                        <button type="submit" class="button-body btn mb-1 btn-lg custom-btn-create button-float">Create Food </button>

                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

EvSef.Web/Areas/AdminPanel/Views/Food/CreateFoodCategoryByAdmin.cshtml
@model EvSef.Domain.ViewModels.FoodCategory.CreateFoodCategoryViewModel
 

@{
    ViewData["Title"] = "CreateFoodCategoryByAdmin";
}


<div class="row page-titles mx-0">
    <div class="col p-md-0">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Dashboard</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Create Food Category</a></li>
        </ol>
    </div>
</div>
<div class="content-body">

    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="basic-form">
                            <form asp-controller="Food" asp-action="CreateFoodCategoryByAdmin" method="post" enctype="multipart/form-data">
                                <div class="form-row"/>
                                <div class="form-group col-md-6">
                                    <label asp-for="FoodCategoryTitle">Food Category Title</label>
                                    <input asp-for="FoodCategoryTitle" type="text" class="form-control" >
                                    <span asp-validation-for="FoodCategoryTitle"></span>
                                </div>

                                <div class="form-check ml-5 mt-5 mb-3">
                                        <input asp-for="IsActive" class="form-check-input" type="checkbox">
                                        <label class="form-check-label">Active</label>
                                    </div>
                              
                                <div class="col-md-12 col-sm-12">
                                    <div class=" ">
                                        <button type="submit" class="button-body btn mb-1 btn-lg custom-btn-create">Create Food Category </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

EvSef.Web/Areas/AdminPanel/Views/Food/CreateFoodSettingByAdmin.cshtml
@model EvSef.Domain.ViewModels.PriceType.CreatePriceTypeViewModel
@{
    ViewData["Title"] = "CreateFoodSettingByAdmin";
}


<div class="row page-titles mx-0">
    <div class="col p-md-0">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Dashboard</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Create Food Setting</a></li>
        </ol>
    </div>
</div>


<div class="content-body">

    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="basic-form">
                            <form asp-controller="Food" asp-action="CreateFoodSettingByAdmin" method="post" enctype="multipart/form-data">
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label asp-for="PriceTypeName">Price Type Name</label>
                                        <input asp-for="PriceTypeName" type="text" class="form-control">
                                        <span asp-validation-for="PriceTypeName"></span>
                                    </div>


                                    <div class="form-group col-md-6">
                                        <label asp-for="PriceTypeCurrency">Price Type Currency</label>
                                        <input asp-for="PriceTypeCurrency" type="text" class="form-control">
                                        <span asp-validation-for="PriceTypeCurrency"></span>
                                    </div>
                              
                                </div>
                              

                                <div class="form-group">
                                    <div class="form-check">
                                        <input id="checkbox" class="form-check-input" type="checkbox" asp-for="PriceTypeIsDefault">
                                        <label for="checkbox" class="form-check-label">Is Default</label>
                                    </div>
                                </div>




                                <div class="col-md-12 col-sm-12">
                                    <div class=" ">
                                        <button type="submit" class="button-body btn mb-1 btn-lg custom-btn-create button-float">Create Price Type </button>

                                    </div>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

EvSef.Web/Areas/AdminPanel/Views/Food/FilterFoodList.cshtml
@using EvSef.Core.FilePath
@using EvSef.Domain.Entities.Account
@using EvSef.Domain.Entities.Food
@using EvSef.Domain.ViewModels.Food
 
@model EvSef.Domain.ViewModels.Food.FilterFoodViewModel
@{
    ViewData["Title"] = "FoodList";
    var viewModel = ViewData["FilterFoodViewModel"] as FilterFoodViewModel;


}


<div class="content-body">

    <div class="row page-titles mx-0">
        <div class="col p-md-0">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Food List</a></li>
            </ol>
        </div>
    </div>

    <div>
        @if (!string.IsNullOrEmpty(ViewBag.ErrorText))
        {
            <div class="content-body-alert card-costum alert alert-danger">
                <p> @ViewBag.ErrorText </p>
            </div>
        }

        @if (!string.IsNullOrEmpty(ViewBag.SuccessText))
        {
            <div class="content-body-alert alert alert-info">
                <p>@ViewBag.SuccessText</p>

            </div>
        }
    </div>
    <!-- row -->

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <form asp-controller="Food" asp-action="FilterFoodList" method="get" id="OurServiceForm">
                     
                    <div class="card">
                        <div class="card-body row">


                            <div class="col-sm-2">
                                <div class="form-group">
                                    <input asp-for="FoodTitle" type="text" class="form-control input-default" placeholder="FoodTitle">
                                </div>
                            </div>

                            <div class="col-sm-2">
                                <div class="form-group">
                                    <input type="text" asp-for="FoodCategories" class="form-control input-default" placeholder="FoodCategories">
                                </div>

                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">

                                    <select class="form-control show-tick" tabindex="-98 " asp-for="FilterFoodState">
                                        <option value="0">All</option>
                                        <option value="1">Active</option>
                                        <option value="2">InActive</option>

                                    </select>
                                </div>
                            </div>

                            <div class="col-sm-2">
                                <button type="submit" class="btn mt-1 btn-secondary">Search</button>
                            </div>

                            <div class="col-md-3 col-sm-12">
                                <div>
                                    <a asp-controller="Food" asp-action="CreateFoodByAdmin" class="button-body btn mb-1 btn-lg custom-btn-create">New Food</a>

                                </div>

                            </div>

                        </div>
                    </div>
                </form>
                <p></p>
                <!-- /# column -->
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            @if (Model.AllEntitiesCount > 0)
                            {
                                <div class="card-title">
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th class="text-center">Photo</th>
                                                <th class="text-center">Food Name</th>
                                                <th class="text-center">Status</th>
                                                <th class="text-center">Food Category</th>
                                                <th class="text-center">Operation</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var food in Model.Foods)
                                            {
                                                <tr>
                                                    @if (food.ImageFood == null)
                                                    {
                                                        <td class="text-center">
                                                            <img class="thumbnail" src="@(FilePath.FoodAvatarImage   + "form-user.png")" style="max-width: 50px" />

                                                        </td>
                                                    }

                                                    else
                                                    {
                                                        <td class="text-center">
                                                            <img class="thumbnail" src="@(FilePath.FoodAvatarImage + food.ImageFood)" style="max-width: 50px" />
                                                        </td>

                                                    }


                                                    <td class="text-center">@food.FoodTitle</td>
                                                    <td class="text-center">


                                                        @if (food.IsActive)
                                                        {
                                                            <i class="   fa fa-check text-success"></i>
                                                        }
                                                        else
                                                        {
                                                            <i class="   fa fa-close text-danger"></i>
                                                        }



                                                    </td>
                                                    <td>
                                                        <ul>
                                                            @foreach (var category in food.FoodSelectedCategories.Select(fsc => fsc.FoodCategory))
                                                            {
                                                                <li class="text-center">@category.FoodCategoryTitle</li>
                                                            }
                                                        </ul>
                                                    </td>
                                                    <td class=" text-center">


                                                        <a title="Edit" data-toggle="tooltip">
                                                            <i class="icon-size mdi mdi-account-edit"></i>
                                                        </a>
                                                        <a title="Delete" data-toggle="tooltip">
                                                            <i class="icon-size mdi mdi-delete"></i>
                                                        </a>
                                                  
                                                
                                                    

                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                </div>


                                @if (Model.AllPageCount > 1)
                                {
                                    <div class="container">
                                        <div class="col col-sm-12 py-3 ">
                                            <ul class="pagination">
                                                @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                                                {
                                                    <li class="paginate_button page-item @((Model.PageId == i) ? "active" : "")">
                                                        <a asp-action="FilterFoodList" asp-route-pageId="@i" PFormId="OurServiceForm" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0" class="page-link">@i</a>
                                                    </li>
                                                }

                                            </ul>
                                        </div>

                                    </div>
                                }
                            }

                            else
                            {
                                <div class="alert alert-danger">
                                    <strong>There Is not any Foods.</strong>
                                </div>
                            }
                            <!-- /# column -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

EvSef.Web/Areas/AdminPanel/Views/Food/FoodSettingList.cshtml
@model IEnumerable<EvSef.Domain.ViewModels.PriceType.AdminListPriceTypeViewModel>
@{
    ViewData["Title"] = "FoodSettingList";
}



<div class="content-body">

    <div class="row page-titles mx-0">
        <div class="col p-md-0">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">FoodSetting List</a></li>
            </ol>
        </div>
    </div>

    <div>
        @if (!string.IsNullOrEmpty(ViewBag.ErrorText))
        {
            <div class="content-body-alert card-costum alert alert-danger">
                <p> @ViewBag.ErrorText </p>
            </div>
        }

        @if (!string.IsNullOrEmpty(ViewBag.SuccessText))
        {
            <div class="content-body-alert alert alert-info">
                <p>@ViewBag.SuccessText</p>

            </div>
        }
    </div>
    <!-- row -->

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <form asp-controller="Food" asp-action="FoodSettingList" method="get" id="OurServiceForm">
             
                    <div class="card">
                        <div class="card-body row">

                   

                            <div class="col-md-3 col-sm-12">
                                <div>
                                    <a asp-controller="Food" asp-action="CreateFoodSettingByAdmin" class="button-body btn mb-1 btn-lg custom-btn-create">New Food Setting</a>

                                </div>

                            </div>

                        </div>
                    </div>
                </form>
                <p></p>
                <!-- /# column -->
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            @if (Model.Any())
                            {
                                <div class="card-title">
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>


                                                <th class="text-center">PriceType Name </th>
                                                <th class="text-center">PriceType Default</th>
                                                <th class="text-center">Operation</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var priceType in Model)
                                            {
                                                <tr>


                                                    <td class="text-center">@priceType.PriceTypeName  </td>


                                                    <td class="text-center">

                                                    @if (priceType.PriceTypeIsDefault==true)
                                                    {
                                                    <i class="fa fa-check text-success"></i>
                                                    
                                                    }
                                                    else
                                                    {
                                                    <i class="fa fa-close text-danger"></i>
                                                    }


                                                    </td>

                                                    <td class="text-center">

                                                        <a title="Edit" data-toggle="tooltip">
                                                            <i class="icon-size mdi mdi-account-edit"></i>
                                                        </a>
                                                        <a title="Delete" data-toggle="tooltip">
                                                            <i class="icon-size mdi mdi-delete"></i>
                                                        </a>


                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                </div>

                            }

                            else
                            {
                                <div class="alert alert-danger">
                                    <strong>There Is not any  Price Type Name.</strong>
                                </div>
                            }
                            <!-- /# column -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>